# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_libros_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='Portada',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
