# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_libros_is_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autores',
            name='libros',
        ),
        migrations.AddField(
            model_name='autores',
            name='libros',
            field=models.ManyToManyField(to='App.Libros'),
        ),
    ]
