# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_auto_20160718_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autores',
            name='libros',
        ),
        migrations.AddField(
            model_name='autores',
            name='libros',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.Libros'),
        ),
    ]
