# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-20 00:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20160718_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='autores',
            name='Foto',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
